// convention: verb + noun + status

// Authentication
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

export const CHECK_ACCESS_TOKEN_VALID_REQUEST =
  'CHECK_ACCESS_TOKEN_VALID_REQUEST'
export const CHECK_ACCESS_TOKEN_VALID_SUCCESS =
  'CHECK_ACCESS_TOKEN_VALID_SUCCESS'
export const CHECK_ACCESS_TOKEN_VALID_FAILURE =
  'CHECK_ACCESS_TOKEN_VALID_FAILURE'

// App Domain
export const FETCH_ALL_APPS_REQUEST = 'FETCH_ALL_APPS_REQUEST'
export const FETCH_ALL_APPS_SUCCESS = 'FETCH_ALL_APPS_SUCCESS'
export const FETCH_ALL_APPS_FAILURE = 'FETCH_ALL_APPS_FAILURE'

export const UPDATE_APP_REQUEST = 'UPDATE_APP_REQUEST'
export const UPDATE_APP_SUCCESS = 'UPDATE_APP_SUCCESS'
export const UPDATE_APP_FAILURE = 'UPDATE_APP_FAILURE'

// App's Users Domain
export const FETCH_APP_USERS_REQUEST = 'FETCH_APP_USERS_REQUEST'
export const FETCH_APP_USERS_SUCCESS = 'FETCH_APP_USERS_SUCCESS'
export const FETCH_APP_USERS_FAILURE = 'FETCH_APP_USERS_FAILURE'
